### ISSUE TITLE
Issuing command twice

### ISSUE THREAD

**Issue by thegeekfox** [fische17/SpartanController#1]
I'm using this with Google Assistant and each command I say will occur twice on my computer. I only have one instance of SpartanController open. I check the text file in my dropbox and it is only appending the text once. What am I doing wrong?

Another question:
Do you have plans on updating the ui or functionality of the program any more?

**Comment by KyleJFischer** [comment]
Hey, I just saw this. Been a bit busy. I updated it recently where it fixes the issuing of the command twice. I have no urgent plans on updating this directly. If other people added features or want something maybe I will look into it but as of now, I just simply don't have the time.
